### ISSUE TITLE
Create demo app for ScienceBeam output displayed in Texture

### ISSUE THREAD

**Issue by BlueReZZ** [eLifePathways/sciencebeam-parser#15]
- [x] Use GROBID XSL to transform title, abstract etc. to JATS
- [x] Load result into Texture locally
- [x] Create Docker image to deploy results of transform and texture to the web
- [x] Deploy to cloud
- [x] Create benchmark transforms and web page to see them in Texture (use eLife, PLoS, Hindawi and an open BMJ article).
- [x] Create API to take PDF and return JATS XML using GROBID XSL
- [x] Create upload PDF -> Texture page
